<?php

function mark_feedclient_menu() {
  $items['mark-feedclient/get-feeds'] = array(
    'title' => 'Hashtag Feed',
    'page callback' => '_mark_feedclient_get_feeds',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/config/services/mark-feedclient'] = array(
    'page callback' => 'drupal_get_form',
    'title' => t('Mark Feed Client Config'),
    'page arguments' => array('_mark_feedclient_config'),
    'description' => 'Configure Feed Client.',
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}

function _mark_feedclient_config(){
  $form = null;
  
  $form['mfc_service_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Service URL'),
    '#default_value' => variable_get('mfc_service_url','http://54.251.245.5/voicestodayfeed/socialfeed/feed.json'),
  );
  $form['mfc_source_hashtag'] = array(
    '#type' => 'textfield',
    '#title' => t('Source Hashtag'),
    '#default_value' => variable_get('mfc_source_hashtag',''),
  );
  $form['mfc_cache_life'] = array(
    '#type' => 'textfield',
    '#title' => t('Cache lifespan'),
    '#default_value' => variable_get('mfc_cache_life','+1 hour'),
  );
  
  return system_settings_form($form);
}

/**
 * Implements hook_block_info().
 */
function mark_feedclient_block_info() {
  $blocks = array();
  $blocks['mfc_text_feed'] = array(
    'info' => t('Mark Feed Client Text Feed'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function mark_feedclient_block_view($delta='') {
  $block = array();
 
  switch($delta) {
    case 'mfc_text_feed' :
      $block['content'] = _mfc_text_feed();
      break;
  }
  
  return $block;
}

function _mfc_text_feed(){
  $module_path = drupal_get_path('module', 'mark_feedclient');
  
  //drupal_add_js(array('mark_feedclient' => array('ajaxURL' => url('mark-feedclient/get-feeds', array('absolute'=>true)))), 'setting');
  drupal_add_js(array('mark_feedclient' => array('ajaxURL' => url('mark-feedclient/get-feeds'))), 'setting');
  drupal_add_js(array('mark_feedclient' => array('sourceHashtag' => variable_get('mfc_source_hashtag',''))), 'setting');
  
  $text_feed = '<div class="mfc-block-text-feed"><div class="mfc-block-text-feed-container"></div></div>';
  
  // Block output in HTML with div wrapper
  $block = array(
    'message' => array(
      '#type' => 'markup',
      '#markup' => $text_feed,
      '#attached' => array(
        'js' => array(
          $module_path . '/js/mfc_text_feed.js' => array (
            'type' => 'file',
            'scope' => 'footer',
          ),
          $module_path . '/js/jquery.marquee.min.js' => array (
            'type' => 'file',
          ),
        ),
        'css' => array(
          $module_path . '/css/mfc_text_feed.css',
        ),
      ),
    ),
  );
 
  return $block;
}

/** hook_theme **/
function mark_feedclient_theme(){
    $themes = array (
      //'today_ndp_page' => array(
      //    'template' => 'templates/today-ndp-page', // your template file called custompage.tpl.php
      //    'variables' => array('args' => NULL),
      //),
      //'today_ndp_voicesfeed_reader' => array(
      //    'template' => 'templates/today-ndp-hashtag-items-reader', // your template file called custompage.tpl.php
      //    'variables' => array('args' => NULL),
      //),
      //'today_ndp_voicesfeed_reader_item' => array(
      //    'template' => 'templates/today-ndp-hashtag-item-reader', // your template file called custompage.tpl.php
      //    'variables' => array('args' => NULL),
      //),
      'mfc_voicesfeed_reader_item' => array(
          'template' => 'templates/mfc-item-reader', // your template file called custompage.tpl.php
          'variables' => array('args' => NULL),
      ),
    );
    return $themes;
}

function _mark_feedclient_get_feeds(){
  $page = 0;
  if(isset($_GET['page']))
    $page = $_GET['page'];
    
  $return_content = _mark_feedclient_get_feeds_array($_GET['source'], $page);
  echo drupal_json_encode($return_content);
}

function _mark_feedclient_get_feeds_array($source, $page){
  //$page = 0;
  //if(isset($_GET['page']))
  //  $page = $_GET['page'];
  //$curl_data = "?source=" . urlencode($_GET['source']) . "&page=" . $page;
  $return_content = array();
  
  $cached = cache_get('mfc_contents_' . urlencode($source) .'_'.$page, 'cache');
  if($cached && $cached->data && ($cached->expire >= strtotime('now'))){
    $return_content = $cached->data;
  }else{
    $curl_data = '?source=' . urlencode($source) . '&page='. $page;
    $service_url = variable_get('mfc_service_url','http://54.251.245.5/voicestodayfeed/socialfeed/feed.json');
    $url = $service_url.$curl_data;
    
    $request =  $url;
    $response = file_get_contents($request);
    
    $response = drupal_json_decode($response);
      
    $themed = '';
    $themed_array = array();
    foreach($response as $key => $item){
      $themed_array[] = theme('mfc_voicesfeed_reader_item', array('args' => array('item' => $item, 'key' => $key)));
    }
    
    $return_content = array(
      'source' => urlencode($_GET['source']),
      'response' => $response,
      'rendered' => $themed,
      'rendered_array' => $themed_array,
    );
    
    $cache_life = variable_get('mfc_cache_life','+1 hour');
    $cache_life = strtotime($cache_life);
    
    cache_set('mfc_contents_' . urlencode($source) .'_'.$page, $return_content, 'cache', $cache_life);
  }
  return $return_content;
}