<?php

/**
 * Implements hook_menu().
 */
function gallery_loader_menu(){  
  $items['node/%/gallery'] = array(
    'page callback' => 'node_gallery_render',
    'page arguments' => array(1),
    'title' => t('Gallery Loader render node'),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'delivery callback' => 'node_gallery_render_callback',  // Magic goes here
  );
  
  return $items;
}

function gallery_loader_init(){
  drupal_add_js(drupal_get_path('module', 'gallery_loader'). '/js/gallery_loader.js');
  //drupal_add_js(drupal_get_path('module', 'gallery_loader'). '/js/jquery.mobile-1.1.2.min.js');
}

function node_gallery_render($nid){
  $node = node_load($nid);
  $view_mode = 'default';
  //return node_view($node, $view_mode);
  $field_name = 'field_media';
  return field_view_field('node', $node, $field_name, $view_mode);
}

function node_gallery_render_callback($page_callback_result){
  // Only render content
  print drupal_render($page_callback_result);
  // Perform end-of-request tasks.
  drupal_page_footer();
}